# Generated by Django 3.1.7 on 2021-04-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('semester_name', models.CharField(max_length=128)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-semester_name',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=128)),
                ('semesters', models.ManyToManyField(related_name='courses', to='course.Semester')),
            ],
            options={
                'ordering': ('-course_name',),
            },
        ),
    ]
