# Generated by Django 3.1.7 on 2021-04-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-course_id',)},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ('-semester_id',)},
        ),
    ]
