# Generated by Django 3.1.7 on 2021-04-11 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20210411_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('course_id',)},
        ),
    ]
