# Generated by Django 3.1.7 on 2021-04-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20210413_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semesters',
            field=models.ManyToManyField(blank=True, related_name='courses', to='course.Semester'),
        ),
    ]
