# Generated by Django 3.1.7 on 2021-04-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20210413_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_status',
            field=models.CharField(default='结课', max_length=128),
        ),
    ]
