# Generated by Django 3.1.7 on 2021-04-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20210413_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_status',
            field=models.CharField(default='close', max_length=128),
        ),
    ]
