# Generated by Django 3.1.7 on 2021-04-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ('school_id',),
            },
        ),
    ]
