# Generated by Django 3.1.7 on 2021-04-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210412_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='read_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
