# Generated by Django 3.1.7 on 2021-04-13 01:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210413_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='read_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
