# Generated by Django 3.1.7 on 2021-04-11 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=128)),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('download_counts', models.BigIntegerField()),
                ('file', models.FileField(upload_to='')),
                ('courses', models.ManyToManyField(related_name='sources', to='course.Course')),
                ('upload_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-source_id',),
            },
        ),
    ]
