# Generated by Django 3.1.7 on 2021-04-10 09:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 9, 26, 24, 654844, tzinfo=utc)),
        ),
    ]
