# Generated by Django 3.1.7 on 2021-04-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_auto_20210411_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='download_counts',
            field=models.BigIntegerField(default=0),
        ),
    ]
