# Generated by Django 3.1.7 on 2021-04-10 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_auto_20210410_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='upload_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
