# Generated by Django 3.1.7 on 2021-04-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_auto_20210411_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ('source_id',)},
        ),
    ]
