# Generated by Django 3.1.7 on 2021-04-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_auto_20210412_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_file',
            field=models.FileField(upload_to='files/%Y%m%d/'),
        ),
    ]
